# Generated by Django 4.2.4 on 2024-06-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_card_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплата"},
        ),
    ]
