# Generated by Django 4.2.4 on 2023-09-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
