# Generated by Django 4.2.4 on 2024-06-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_products_alter_order_address_alter_order_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="basket",
        ),
        migrations.RemoveField(
            model_name="basketitem",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.DeleteModel(
            name="Basket",
        ),
        migrations.DeleteModel(
            name="BasketItem",
        ),
    ]
