# Generated by Django 4.2.4 on 2023-08-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_avatar_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="src",
            field=models.ImageField(
                default="avatars/default.png",
                upload_to="avatars/user_avatars/",
                verbose_name="Ссылка",
            ),
        ),
    ]
