# Generated by Django 4.2.4 on 2023-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_avatar_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="alt",
            field=models.CharField(max_length=128, null=True, verbose_name="Описание"),
        ),
    ]
