# Generated by Django 4.2.4 on 2023-08-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_avatar_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="alt",
            field=models.CharField(
                default="Описание картинки", max_length=128, verbose_name="Описание"
            ),
        ),
    ]
