# Generated by Django 4.2.4 on 2023-08-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.image",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="category", to="catalog.subcategory"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="alt",
            field=models.CharField(
                default="Описание картинки",
                max_length=128,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="src",
            field=models.ImageField(
                default="category/default.png",
                null=True,
                upload_to="category/pictures/",
                verbose_name="Ссылка",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.subimage",
            ),
        ),
        migrations.AlterField(
            model_name="subimage",
            name="alt",
            field=models.CharField(
                default="Описание картинки",
                max_length=128,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="subimage",
            name="src",
            field=models.ImageField(
                default="subcategory/default.png",
                null=True,
                upload_to="subcategory/pictures/",
                verbose_name="Ссылка",
            ),
        ),
    ]
