# Generated by Django 4.2.4 on 2023-08-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_subcategory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="src",
            field=models.ImageField(
                default="category/default.png",
                upload_to="category/pictures/",
                verbose_name="Ссылка",
            ),
        ),
        migrations.AlterField(
            model_name="subimage",
            name="src",
            field=models.ImageField(
                default="subcategory/default.png",
                upload_to="subcategory/pictures/",
                verbose_name="Ссылка",
            ),
        ),
    ]
