# Generated by Django 4.2.4 on 2023-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_image_src_alter_subimage_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subimage",
            name="alt",
            field=models.CharField(
                default="Описание картинки", max_length=128, verbose_name="Описание"
            ),
        ),
    ]
