# Generated by Django 4.2.4 on 2023-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_subimage_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, related_name="category", to="catalog.subcategory"
            ),
        ),
        migrations.AlterField(
            model_name="subimage",
            name="alt",
            field=models.CharField(
                default="Описание картинки",
                max_length=128,
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
