# Generated by Django 4.2.4 on 2023-08-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.subimage",
            ),
        ),
    ]
