# Generated by Django 4.2.4 on 2023-08-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_productimage_review_specification_tag_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.category",
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.RemoveField(
            model_name="product",
            name="reviews",
        ),
        migrations.RemoveField(
            model_name="product",
            name="specifications",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(to="catalog.productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.ManyToManyField(to="catalog.review"),
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(to="catalog.specification"),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="catalog.tag"),
        ),
    ]
