# Generated by Django 4.2.4 on 2023-08-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_alter_product_category_remove_product_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
