# Generated by Django 4.2.4 on 2023-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_review_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="fullDescription",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(blank=True, to="catalog.specification"),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="catalog.tag"),
        ),
    ]
