# Generated by Django 4.2.4 on 2023-08-25 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_alter_product_date_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.CharField(
                blank=True, default=datetime.date(2023, 8, 25), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="fullDescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(blank=True, to="catalog.productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="reviews",
            field=models.ManyToManyField(blank=True, to="catalog.review"),
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.CharField(
                blank=True,
                default=datetime.date(2023, 8, 25),
                max_length=100,
                null=True,
            ),
        ),
    ]
