# Generated by Django 4.2.4 on 2023-08-30 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_sale_alter_product_date_alter_review_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sale",
        ),
        migrations.AddField(
            model_name="sale",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.CharField(
                blank=True, default=datetime.date(2023, 8, 30), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.CharField(
                blank=True,
                default=datetime.date(2023, 8, 30),
                max_length=100,
                null=True,
            ),
        ),
    ]
