# Generated by Django 4.2.4 on 2023-08-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog",
            "0018_remove_product_sale_sale_product_alter_product_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.sale",
            ),
        ),
    ]
