# Generated by Django 4.2.4 on 2024-06-30 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_alter_product_date_alter_review_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Изображение продукта",
                "verbose_name_plural": "Изображения продукта",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"verbose_name": "Скидка", "verbose_name_plural": "Скидки"},
        ),
        migrations.AlterModelOptions(
            name="specification",
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AlterModelOptions(
            name="subimage",
            options={
                "verbose_name": "Изображение подкатегории",
                "verbose_name_plural": "Изображения подкатегории",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.CharField(
                blank=True, default=datetime.date(2024, 6, 30), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.CharField(
                blank=True,
                default=datetime.date(2024, 6, 30),
                max_length=100,
                null=True,
            ),
        ),
    ]
